// All 86 test scenarios for First Choice Imaging voice agent testing
// Each scenario defines a persona, opening line, and expected behavior

export const scenarios = [
  // ══════════════════════════════════════════════════════════════════════
  // SCHEDULING (S-01 to S-07) — Expected: Transfer to Scheduling
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'S-01', category: 'Scheduling',
    persona: 'Sarah Mitchell, patient',
    phone: '4355550101',
    opening: 'Hi, I need to schedule an MRI.',
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Collects name/phone, then immediately transfers to Scheduling. No records questions.',
  },
  {
    id: 'S-02', category: 'Scheduling',
    persona: 'David Park, patient',
    phone: '8015550102',
    opening: "I have an appointment coming up and I can't remember what time it's at.",
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Transfers to Scheduling. Does NOT guess appointment times.',
  },
  {
    id: 'S-03', category: 'Scheduling',
    persona: 'Maria Lopez, patient',
    phone: '4355550103',
    opening: 'I need to reschedule my MRI. Something came up.',
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Transfer to Scheduling. No attempt to reschedule directly.',
  },
  {
    id: 'S-04', category: 'Scheduling',
    persona: 'James Chen, patient',
    phone: '8015550104',
    opening: 'I need to cancel my appointment.',
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Transfer to Scheduling. Agent does not cancel anything.',
  },
  {
    id: 'S-05', category: 'Scheduling',
    persona: 'Linda Harris, patient',
    phone: '4355550105',
    opening: "My doctor said they sent over an order for my MRI. Have you guys received it?",
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Does not fabricate an answer. Transfers to Scheduling or Receptionist.',
  },
  {
    id: 'S-06', category: 'Scheduling',
    persona: 'Tom Baker, patient',
    phone: '8015550106',
    opening: 'Do you have any openings this week for an MRI?',
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Does not fabricate availability. Transfers to Scheduling.',
  },
  {
    id: 'S-07', category: 'Scheduling',
    persona: 'Karen White, patient',
    phone: '4355550107',
    opening: "I don't have a doctor's order but I want to get an MRI. Can I do that?",
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Explains self-referral (non-contrast MRI, self-pay only). Offers transfer to Scheduling.',
  },

  // ══════════════════════════════════════════════════════════════════════
  // PRICING (PR-01 to PR-07) — Expected: Transfer to Scheduling, no prices
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'PR-01', category: 'Pricing',
    persona: 'Rachel Green, patient',
    phone: '8015550201',
    opening: 'How much does an MRI cost?',
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Cannot provide pricing over the phone. Offers transfer to Scheduling. Zero pricing shared.',
  },
  {
    id: 'PR-02', category: 'Pricing',
    persona: 'Mike Johnson, patient',
    phone: '4355550202',
    opening: "What does an arthrogram run? I'm trying to budget for it.",
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'No pricing. Transfer offered.',
  },
  {
    id: 'PR-03', category: 'Pricing',
    persona: 'Amy Wilson, patient',
    phone: '8015550203',
    opening: 'I need a CT scan. How much is that going to cost me?',
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Mentions CT at North Logan. No pricing. Transfer offered.',
  },
  {
    id: 'PR-04', category: 'Pricing',
    persona: 'Jessica Taylor, patient',
    phone: '4355550204',
    opening: 'How much is an ultrasound?',
    expectedTransfer: null,
    expectedBehavior: 'States ultrasound NOT at Logan/North Logan. Mentions Tooele. No pricing.',
  },
  {
    id: 'PR-05', category: 'Pricing',
    persona: 'Brian Adams, patient',
    phone: '8015550205',
    opening: 'How much for an X-ray?',
    expectedTransfer: null,
    expectedBehavior: 'States X-ray NOT at Logan/North Logan. Mentions Tooele and St. George. No pricing.',
  },
  {
    id: 'PR-06', category: 'Pricing',
    persona: 'Susan Clark, patient',
    phone: '4355550206',
    opening: "What's the price for a DEXA scan?",
    expectedTransfer: null,
    expectedBehavior: 'DEXA not at Logan/North Logan. Mentions Tooele. No pricing.',
  },
  {
    id: 'PR-07', category: 'Pricing',
    persona: 'Robert Martinez, patient',
    phone: '8015550207',
    opening: 'Do you accept insurance? Are you in network with Blue Cross?',
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Does not fabricate insurance info. Transfers to Scheduling or Billing.',
  },

  // ══════════════════════════════════════════════════════════════════════
  // BILLING (B-01 to B-10) — Expected: Transfer to Billing
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'B-01', category: 'Billing',
    persona: 'Nancy Turner, patient',
    phone: '4355550301',
    opening: "I got a bill in the mail and I'd like to pay it.",
    expectedTransfer: 'Billing',
    expectedBehavior: 'Transfers to Billing. Does not attempt to take payment.',
  },
  {
    id: 'B-02', category: 'Billing',
    persona: 'Frank Morris, patient',
    phone: '8015550302',
    opening: "I have a question about my bill. There's a charge I don't understand.",
    expectedTransfer: 'Billing',
    expectedBehavior: 'Transfer to Billing.',
  },
  {
    id: 'B-03', category: 'Billing',
    persona: 'Patricia Lee, patient',
    phone: '4355550303',
    opening: 'I need an itemized statement of my charges.',
    expectedTransfer: 'Billing',
    expectedBehavior: 'Transfer to Billing. NOT routed to Medical Records.',
  },
  {
    id: 'B-04', category: 'Billing',
    persona: 'George Hall, patient',
    phone: '8015550304',
    opening: 'I need a receipt for the payment I made last month.',
    expectedTransfer: 'Billing',
    expectedBehavior: 'Transfer to Billing.',
  },
  {
    id: 'B-05', category: 'Billing',
    persona: 'Dorothy King, patient',
    phone: '4355550305',
    opening: 'Can I get a history of all my payments?',
    expectedTransfer: 'Billing',
    expectedBehavior: 'Transfer to Billing.',
  },
  {
    id: 'B-06', category: 'Billing',
    persona: 'Richard Scott, patient',
    phone: '8015550306',
    opening: "There's a charge on my bill that I don't think is right. I want to dispute it.",
    expectedTransfer: 'Billing',
    expectedBehavior: 'Transfer to Billing. Agent does not adjudicate.',
  },
  {
    id: 'B-07', category: 'Billing',
    persona: 'Sandra Young, patient',
    phone: '4355550307',
    opening: 'I need a copy of all the charges from my visit.',
    expectedTransfer: 'Billing',
    expectedBehavior: 'Transfer to Billing.',
  },
  {
    id: 'B-08', category: 'Billing',
    persona: 'Kevin Wright, patient',
    phone: '8015550308',
    opening: 'I need to update my address on file.',
    expectedTransfer: 'Billing',
    expectedBehavior: 'Routes to a human (Billing or Receptionist). Does not update directly.',
  },
  {
    id: 'B-09', category: 'Billing',
    persona: 'Laura Hill, patient',
    phone: '4355550309',
    opening: 'I need a copy of my billing records for my personal files.',
    expectedTransfer: null,
    expectedBehavior: 'CRITICAL EXCEPTION: Routes through Medical Records workflow, NOT Billing. Should ask caller type, offer form link.',
  },
  {
    id: 'B-10', category: 'Billing',
    persona: 'Mark Davis, attorney at Davis and Associates',
    phone: '8015550310',
    opening: "I'm an attorney and I need billing statements for one of your patients.",
    expectedTransfer: null,
    expectedBehavior: 'Attorney path. Asks records or lien. Verbal URL, no SMS.',
  },

  // ══════════════════════════════════════════════════════════════════════
  // RECORDS — PATIENT (RP-01 to RP-09) — Dashboard workflow
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'RP-01', category: 'Records-Patient',
    persona: 'Emily Watson, patient',
    phone: '4355550401',
    opening: 'I had an MRI last week and I need a copy of my report.',
    expectedTransfer: null,
    expectedBehavior: 'Records workflow: patient → radiology_report → SMS link offer. All variables set.',
  },
  {
    id: 'RP-02', category: 'Records-Patient',
    persona: 'Chris Anderson, patient',
    phone: '8015550402',
    opening: "I'm trying to log into the patient portal but it's not working.",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Patient portal suspended. Transfer to Receptionist.',
  },
  {
    id: 'RP-03', category: 'Records-Patient',
    persona: 'Angela Thomas, patient',
    phone: '4355550403',
    opening: "I need my results sent to my doctor. He says he hasn't gotten them yet.",
    expectedTransfer: null,
    expectedBehavior: 'Records workflow or transfer to Receptionist. Does not claim to send results directly.',
  },
  {
    id: 'RP-04', category: 'Records-Patient',
    persona: 'Jeff Robinson, patient',
    phone: '8015550404',
    opening: "My doctor says they never got my MRI results. It's been two weeks.",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Cannot verify delivery. Routes to Receptionist. Does NOT fabricate status.',
  },
  {
    id: 'RP-05', category: 'Records-Patient',
    persona: 'Diane Jackson, patient',
    phone: '4355550405',
    opening: 'I need a copy of my medical records.',
    expectedTransfer: null,
    expectedBehavior: 'Full records workflow: patient → medical_records → form link. All variables set.',
  },
  {
    id: 'RP-06', category: 'Records-Patient',
    persona: 'Paul White, patient',
    phone: '8015550406',
    opening: 'I need a disc of my MRI images.',
    expectedTransfer: null,
    expectedBehavior: 'Records workflow: patient → medical_records → form. Variables set.',
  },
  {
    id: 'RP-07', category: 'Records-Patient',
    persona: 'Carol Martin, patient',
    phone: '4355550407',
    opening: 'Can you email me my MRI images?',
    expectedTransfer: null,
    expectedBehavior: 'Treated as records request. Directs to form. Does NOT promise to email directly.',
  },
  {
    id: 'RP-08', category: 'Records-Patient',
    persona: 'Harold Brown, elderly patient (landline)',
    phone: '4355550408',
    opening: "I need my records but I don't have a cell phone — I'm calling from my home phone.",
    expectedTransfer: null,
    expectedBehavior: 'Verbal URL fallback when SMS declined. sms_consent = NO. Workflow completes.',
    followUp: "No, I can't get texts on this phone.",
  },
  {
    id: 'RP-09', category: 'Records-Patient',
    persona: 'Lisa Garcia, patient',
    phone: '8015550409',
    opening: 'I need a copy of my records and also a separate radiology report for my attorney.',
    expectedTransfer: null,
    expectedBehavior: 'Multi-intent handling. Variables not overwritten.',
  },

  // ══════════════════════════════════════════════════════════════════════
  // RECORDS — PROVIDER (RV-01 to RV-10) — Transfer to Receptionist
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'RV-01', category: 'Records-Provider',
    persona: "Dr. Amanda Foster's office",
    phone: '4355550501',
    opening: "This is Dr. Foster's office calling. We need MRI results faxed over for a patient.",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Provider path → electronic → PACS/portal → transfer to Receptionist.',
  },
  {
    id: 'RV-02', category: 'Records-Provider',
    persona: 'Jenny, radiology tech at Valley Medical',
    phone: '8015550502',
    opening: 'Hi, I need images pushed through PowerShare for one of our patients.',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Provider path → transfer to Receptionist.',
  },
  {
    id: 'RV-03', category: 'Records-Provider',
    persona: 'Dr. Kevin Nguyen',
    phone: '4355550503',
    opening: 'I need to get access to your PACS system.',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Provider portal or transfer to Receptionist.',
  },
  {
    id: 'RV-04', category: 'Records-Provider',
    persona: 'Dr. Sarah Kim, out-of-state provider',
    phone: '8015550504',
    opening: "I'm an out-of-state provider and I need images mailed to my office.",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Provider → disc → form → transfer to Receptionist.',
  },
  {
    id: 'RV-05', category: 'Records-Provider',
    persona: 'Dr. Michael Reed',
    phone: '4355550505',
    opening: 'I need an addendum on an MRI report for one of my patients.',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Transfer to Receptionist. No attempt to modify reports.',
  },
  {
    id: 'RV-06', category: 'Records-Provider',
    persona: 'Dr. Lisa Chang',
    phone: '8015550506',
    opening: "I need a comparison done with the patient's previous imaging from another facility.",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Transfer to Receptionist.',
  },
  {
    id: 'RV-07', category: 'Records-Provider',
    persona: 'Nurse Practitioner office',
    phone: '4355550507',
    opening: "We're still waiting on a read for a CT we sent a patient for three days ago.",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Transfer to Receptionist. Does not fabricate read status.',
  },
  {
    id: 'RV-08', category: 'Records-Provider',
    persona: 'Dr. office staff',
    phone: '8015550508',
    opening: "When can we expect the read to be done on our patient's MRI?",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Transfer to Receptionist. No fabricated timeline.',
  },
  {
    id: 'RV-09', category: 'Records-Provider',
    persona: 'Dr. Williams',
    phone: '4355550509',
    opening: "I need to talk to someone about a read. I think there's an error.",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Valid complaint → transfer to Receptionist.',
  },
  {
    id: 'RV-10', category: 'Records-Provider',
    persona: 'New provider office',
    phone: '8015550510',
    opening: 'We have a patient with knee pain. What should we order?',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Does NOT recommend a scan. Transfers.',
  },

  // ══════════════════════════════════════════════════════════════════════
  // RECORDS — ATTORNEY (RA-01 to RA-04)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'RA-01', category: 'Records-Attorney',
    persona: 'Jennifer Blake, paralegal at Smith and Associates',
    phone: '8015550601',
    opening: "I'm calling from a law firm. We need medical records for one of your patients who is our client.",
    expectedTransfer: null,
    expectedBehavior: 'Attorney records path. Verbal URL. No SMS offered. sms_consent = NO.',
  },
  {
    id: 'RA-02', category: 'Records-Attorney',
    persona: 'Attorney Daniel Hart',
    phone: '4355550602',
    opening: "I'm an attorney. I need medical records for a personal injury case.",
    expectedTransfer: null,
    expectedBehavior: 'Attorney records workflow. All variables set.',
  },
  {
    id: 'RA-03', category: 'Records-Attorney',
    persona: 'Maria Santos, paralegal at Rivera Law Group',
    phone: '8015550603',
    opening: "I'm calling from Rivera Law Group. We'd like to set up a direct lien for a patient.",
    expectedTransfer: null,
    expectedBehavior: 'Full lien collection. All 11 steps. Email spelled back. sms_consent = NO. intents_handled = lien.',
    lienTestData: {
      patientName: 'John Rivera',
      dob: 'March fifteenth, nineteen eighty-two',
      firmName: 'Rivera Law Group',
      attorney: 'Carlos Rivera',
      contact: 'That would be me, Maria Santos',
      email: 'maria at riveralaw dot com',
      location: 'Yes, Logan',
    },
  },
  {
    id: 'RA-04', category: 'Records-Attorney',
    persona: 'Legal assistant at a law firm',
    phone: '4355550604',
    opening: "We represent a patient and need to know when they're scheduled for their MRI.",
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Cannot look up schedules. Transfers.',
  },

  // ══════════════════════════════════════════════════════════════════════
  // GENERAL PROVIDER (GP-01 to GP-14)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'GP-01', category: 'General-Provider',
    persona: 'Dr. office calling about a patient',
    phone: '4355550701',
    opening: 'We referred a patient for an MRI last week. Has she been scheduled yet?',
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Cannot look up. Transfers.',
  },
  {
    id: 'GP-02', category: 'General-Provider',
    persona: 'Ordering provider',
    phone: '8015550702',
    opening: 'What protocol do you use for a lumbar spine MRI with contrast?',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Does not guess protocol. Routes to human.',
  },
  {
    id: 'GP-03', category: 'General-Provider',
    persona: 'New provider',
    phone: '4355550703',
    opening: 'My patient has shoulder pain after a fall. What imaging should I order?',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'NO scan recommendation. Transfers.',
  },
  {
    id: 'GP-04', category: 'General-Provider',
    persona: 'Provider office staff',
    phone: '8015550704',
    opening: 'I need to talk to someone about a prior authorization.',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Transfer to Receptionist or Scheduling.',
  },
  {
    id: 'GP-05', category: 'General-Provider',
    persona: 'Referring provider',
    phone: '4355550705',
    opening: "Can I speak to one of your MRI techs? I have a question about a patient's scan.",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Transfer to Receptionist.',
  },
  {
    id: 'GP-06', category: 'General-Provider',
    persona: 'Referring physician',
    phone: '8015550706',
    opening: 'I need to speak with the radiologist about a read.',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Transfer to Receptionist.',
  },
  {
    id: 'GP-07', category: 'General-Provider',
    persona: 'Provider office',
    phone: '4355550707',
    opening: 'I need to schedule one of my patients for a CT scan.',
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Notes CT at North Logan. Transfers to Scheduling.',
  },
  {
    id: 'GP-08', category: 'General-Provider',
    persona: 'Clinic coordinator',
    phone: '8015550708',
    opening: 'Do you have any MRI slots open this week? We have several patients to send over.',
    expectedTransfer: 'Scheduling',
    expectedBehavior: 'Cannot see calendar. Transfers.',
  },
  {
    id: 'GP-09', category: 'General-Provider',
    persona: 'Provider office',
    phone: '4355550709',
    opening: 'Our patient has a spinal cord stimulator. Can they still get an MRI at your facility?',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Does not definitively say yes or no. Routes for clinical evaluation.',
  },
  {
    id: 'GP-10', category: 'General-Provider',
    persona: 'Provider returning a call',
    phone: '8015550710',
    opening: "I'm returning a call from someone at your office. I didn't catch the name.",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Transfer to Receptionist.',
  },
  {
    id: 'GP-11', category: 'General-Provider',
    persona: 'Provider office',
    phone: '4355550711',
    opening: "We're trying to pull up images on PACS and it's not working.",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Transfer to Receptionist.',
  },
  {
    id: 'GP-12', category: 'General-Provider',
    persona: 'Dr. office staff',
    phone: '8015550712',
    opening: 'I forgot my PACS password. Can you help me reset it?',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Transfer to Receptionist.',
  },
  {
    id: 'GP-13', category: 'General-Provider',
    persona: 'New clinic setting up PACS',
    phone: '4355550713',
    opening: 'We are a new clinic and need to get set up with PACS access.',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'May mention provider portal. Transfers to Receptionist.',
  },
  {
    id: 'GP-14', category: 'General-Provider',
    persona: 'Provider office',
    phone: '8015550714',
    opening: "We're trying to send an order over but we're not sure how.",
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Transfer to Receptionist or Scheduling.',
  },

  // ══════════════════════════════════════════════════════════════════════
  // GENERAL PATIENT (GQ-01 to GQ-17)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'GQ-01', category: 'General-Patient',
    persona: 'Casual caller',
    phone: '4355550801',
    opening: 'What are your hours?',
    expectedTransfer: null,
    expectedBehavior: 'Clarifies intent first. Correct hours: Mon-Fri 6:30 AM - 8:00 PM.',
  },
  {
    id: 'GQ-02', category: 'General-Patient',
    persona: 'Patient',
    phone: '8015550802',
    opening: "What's your fax number?",
    expectedTransfer: null,
    expectedBehavior: 'Provides fax if known. Otherwise transfers to Receptionist.',
  },
  {
    id: 'GQ-03', category: 'General-Patient',
    persona: 'Patient',
    phone: '4355550803',
    opening: 'What email address can I send my insurance card to?',
    expectedTransfer: null,
    expectedBehavior: 'Provides email if known. Otherwise transfers to Receptionist.',
  },
  {
    id: 'GQ-04', category: 'General-Patient',
    persona: 'Patient',
    phone: '8015550804',
    opening: 'Do you do MRIs at this location?',
    expectedTransfer: null,
    expectedBehavior: 'Yes — Logan offers Wide Bore MRI. May mention details.',
  },
  {
    id: 'GQ-05', category: 'General-Patient',
    persona: 'Patient',
    phone: '4355550805',
    opening: 'Can I get a CT scan there?',
    expectedTransfer: null,
    expectedBehavior: 'CT at North Logan CT Clinic, same phone line.',
  },
  {
    id: 'GQ-06', category: 'General-Patient',
    persona: 'Patient',
    phone: '8015550806',
    opening: 'Do you offer X-rays?',
    expectedTransfer: null,
    expectedBehavior: 'NOT at Logan/North Logan. Available at Tooele and St. George.',
  },
  {
    id: 'GQ-07', category: 'General-Patient',
    persona: 'Patient',
    phone: '4355550807',
    opening: 'I need an ultrasound. Can I get one there?',
    expectedTransfer: null,
    expectedBehavior: 'NOT at Logan/North Logan. Available at Tooele (Mon & Thu).',
  },
  {
    id: 'GQ-08', category: 'General-Patient',
    persona: 'Patient',
    phone: '8015550808',
    opening: 'Do you do bone density scans?',
    expectedTransfer: null,
    expectedBehavior: 'DEXA not at Logan/North Logan. Available at Tooele.',
  },
  {
    id: 'GQ-09', category: 'General-Patient',
    persona: 'Patient on the way',
    phone: '4355550809',
    opening: "Can you give me directions? I'm on my way.",
    expectedTransfer: null,
    expectedBehavior: 'Asks which location. Offers Google Maps link or verbal address.',
  },
  {
    id: 'GQ-10', category: 'General-Patient',
    persona: 'Nonprofit representative',
    phone: '8015550810',
    opening: "We're a local nonprofit. Can we discuss a sponsorship?",
    expectedTransfer: null,
    expectedBehavior: 'Solicitation — politely declined. Website contact form. No transfer.',
  },
  {
    id: 'GQ-11', category: 'General-Patient',
    persona: 'Marketing company',
    phone: '4355550811',
    opening: "Hi, I'm with a digital marketing agency. I'd love to talk to someone about your online presence.",
    expectedTransfer: null,
    expectedBehavior: 'Solicitation protocol: decline, website if persistent.',
  },
  {
    id: 'GQ-12', category: 'General-Patient',
    persona: 'Unhappy patient',
    phone: '8015550812',
    opening: 'I had a terrible experience at your clinic and I want to file a complaint.',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Valid complaint → transfer to Receptionist.',
  },
  {
    id: 'GQ-13', category: 'General-Patient',
    persona: 'Frustrated caller',
    phone: '4355550813',
    opening: 'I want to speak to a manager.',
    expectedTransfer: 'Receptionist',
    expectedBehavior: 'Live operator protocol. Manager request is valid → transfer.',
  },
  {
    id: 'GQ-14', category: 'General-Patient',
    persona: 'Caller who wants a human',
    phone: '8015550814',
    opening: 'Can I talk to a real person?',
    expectedTransfer: 'Scheduling',
    expectedBehavior: '3-step protocol. Once scheduling revealed, transfer to Scheduling.',
    followUp: ['I just want to talk to someone.', "It's about scheduling."],
  },
  {
    id: 'GQ-15', category: 'General-Patient',
    persona: 'Busy patient',
    phone: '4355550815',
    opening: "I can't stay on the phone right now. Can someone call me back?",
    expectedTransfer: null,
    expectedBehavior: 'Collects name and phone. Acknowledges callback request.',
  },
  {
    id: 'GQ-16', category: 'General-Patient',
    persona: 'Unsure patient',
    phone: '8015550816',
    opening: 'Do I need a doctor\'s order to get an MRI?',
    expectedTransfer: null,
    expectedBehavior: 'Explains self-referral (non-contrast MRI, self-pay). No scan recommendation.',
  },
  {
    id: 'GQ-17', category: 'General-Patient',
    persona: 'Patient',
    phone: '4355550817',
    opening: 'Do you offer mammograms?',
    expectedTransfer: null,
    expectedBehavior: 'No mammograms at any location. Suggests primary care provider. No external referral.',
  },

  // ══════════════════════════════════════════════════════════════════════
  // EDGE CASES (E-01 to E-08)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'E-01', category: 'Edge-Case',
    persona: 'Patient researching options',
    phone: '8015550901',
    opening: 'What Tesla is your MRI machine?',
    expectedTransfer: null,
    expectedBehavior: 'Shares specs if known. Does NOT fabricate.',
  },
  {
    id: 'E-02', category: 'Edge-Case',
    persona: 'Larger patient',
    phone: '4355550902',
    opening: "I'm a bigger person. What's the weight limit on your MRI machine?",
    expectedTransfer: null,
    expectedBehavior: 'Logan MRI 1: 500 lbs, MRI 2 Mobile: 250 lbs. St. George Open MRI: 650 lbs.',
  },
  {
    id: 'E-03', category: 'Edge-Case',
    persona: 'Claustrophobic patient',
    phone: '8015550903',
    opening: "I'm really claustrophobic. Do you have an Open MRI?",
    expectedTransfer: null,
    expectedBehavior: 'Wide Bore (not open). Open MRI only at St. George (650 lbs).',
  },
  {
    id: 'E-04', category: 'Edge-Case',
    persona: 'Silent caller',
    phone: null,
    opening: null,
    expectedTransfer: null,
    expectedBehavior: 'Silence protocol: 4s → 4s → 5s → end call.',
  },
  {
    id: 'E-05', category: 'Edge-Case',
    persona: 'Privacy-conscious caller',
    phone: '4355550905',
    opening: "I just have a quick question about your hours. I don't want to give my name.",
    expectedTransfer: null,
    expectedBehavior: 'Attempts name collection. Does not skip Steps 1-2.',
    followUp: "I'd really rather not. Can you just tell me your hours?",
  },
  {
    id: 'E-06', category: 'Edge-Case',
    persona: 'Alex Turner (refuses phone number)',
    phone: null,
    opening: 'My name is Alex Turner.',
    expectedTransfer: null,
    expectedBehavior: 'Tries twice per Step 2 scripts. Does not fabricate a number.',
    followUp: ["I don't want to give my number. I just need to know your hours.", "I really don't want to. Can you just help me?"],
  },
  {
    id: 'E-07', category: 'Edge-Case',
    persona: 'Attorney with two requests',
    phone: '8015550907',
    opening: "I'm an attorney. I need medical records for one client, and I also need to set up a lien for a different client.",
    expectedTransfer: null,
    expectedBehavior: 'Both workflows completed. intents_handled = "records,lien". No variable overwrites.',
    lienTestData: {
      patientName: 'Sarah Thompson',
      dob: 'June tenth, nineteen ninety',
      firmName: 'Hart and Associates',
      attorney: "That's me",
      contact: 'Myself',
      email: 'attorney at hartlaw dot com',
      location: 'Logan',
    },
  },
  {
    id: 'E-08', category: 'Edge-Case',
    persona: 'Patient who called wrong location',
    phone: '4355550908',
    opening: 'Oh wait, I thought I was calling the Tooele clinic.',
    expectedTransfer: 'Tewilla',
    expectedBehavior: 'Provides Tooele number. Offers transfer. Says "Tewilla" not "Tooele".',
  },
];
